export const brandlogos = [
{
  id:1,
  src:"/brandlogos/fa-brands_aws.png",
},
{
  id:2,
  src:"/brandlogos/fa-brands_hooli.png",
},
{
  id:3,
  src:"/brandlogos/fa-brands_lyft.png",
},
{
  id:4,
  src:"/brandlogos/fa-brands_pied-piper-hat.png"
},
{
  id:5,
  src:"/brandlogos/fa-brands_reddit-alien.png"
},
{
  id:6,
  src:"/brandlogos/fa-brands_stripe.png"
},
]